// online
export const dateTypes = [
  { id: 1, title: "Article", value: "article" },
  { id: 2, title: "Upload", value: "upload" },
];
export const qc1Array = [
  {
    id: 1,
    option: "Yes",
    value: 1,
  },
  {
    id: 2,
    option: "No",
    value: "0",
  },
  {
    id: 3,
    option: " QC1 All",
    value: 2,
  },
];
export const qc1ArrayWithPartially = [
  {
    id: 1,
    option: "Yes",
    value: 1,
  },
  {
    id: 2,
    option: "No",
    value: "0",
  },
  {
    id: 3,
    option: "QC1 All",
    value: 2,
  },
  {
    id: 4,
    option: "Partially Yes",
    value: 3,
  },
  {
    id: 5,
    option: "Partially No",
    value: 4,
  },
];
export const qc2Array = [
  {
    id: 1,
    option: "Yes",
    value: 1,
  },
  {
    id: 2,
    option: "No",
    value: "0",
  },
  {
    id: 3,
    option: " QC2 All",
    value: 2,
  },
];
export const continents = ["Africa", "Asia", "Europe", "America", "Australia"];
export const countriesByContinent = [
  {
    continent: "Africa",
    countries: [
      "Algeria",
      "Angola",
      "Benin",
      "Botswana",
      "Burkina Faso",
      "Burundi",
      "Cameroon",
      "Cape Verde",
      "Central African Republic",
      "Chad",
      "Comoros",
      "Democratic Republic of the Congo",
      "Djibouti",
      "Egypt",
      "Equatorial Guinea",
      "Eritrea",
      "Eswatini",
      "Ethiopia",
      "Gabon",
      "Gambia",
      "Ghana",
      "Guinea",
      "Guinea-Bissau",
      "Ivory Coast",
      "Kenya",
      "Lesotho",
      "Liberia",
      "Libya",
      "Madagascar",
      "Malawi",
      "Mali",
      "Mauritania",
      "Mauritius",
      "Morocco",
      "Mozambique",
      "Namibia",
      "Niger",
      "Nigeria",
      "Rwanda",
      "Sao Tome and Principe",
      "Senegal",
      "Seychelles",
      "Sierra Leone",
      "Somalia",
      "South Africa",
      "South Sudan",
      "Sudan",
      "Tanzania",
      "Togo",
      "Tunisia",
      "Uganda",
      "Zambia",
      "Zimbabwe",
    ],
  },

  {
    continent: "Asia",
    countries: [
      "Afghanistan",
      "Armenia",
      "Azerbaijan",
      "Bahrain",
      "Bangladesh",
      "Bhutan",
      "Brunei",
      "Cambodia",
      "China",
      "Cyprus",
      "Georgia",
      "India",
      "Indonesia",
      "Iran",
      "Iraq",
      "Israel",
      "Japan",
      "Jordan",
      "Kazakhstan",
      "Kuwait",
      "Kyrgyzstan",
      "Laos",
      "Lebanon",
      "Malaysia",
      "Maldives",
      "Mongolia",
      "Myanmar",
      "Nepal",
      "North Korea",
      "Oman",
      "Pakistan",
      "Palestine",
      "Philippines",
      "Qatar",
      "Saudi Arabia",
      "Singapore",
      "South Korea",
      "Sri Lanka",
      "Syria",
      "Taiwan",
      "Tajikistan",
      "Thailand",
      "Timor-Leste",
      "Turkey",
      "Turkmenistan",
      "United Arab Emirates",
      "Uzbekistan",
      "Vietnam",
      "Yemen",
    ],
  },
  {
    continent: "Europe",
    countries: [
      "Albania",
      "Andorra",
      "Armenia",
      "Austria",
      "Azerbaijan",
      "Belarus",
      "Belgium",
      "Bosnia and Herzegovina",
      "Bulgaria",
      "Croatia",
      "Cyprus",
      "Czech Republic",
      "Denmark",
      "Estonia",
      "Finland",
      "France",
      "Georgia",
      "Germany",
      "Greece",
      "Hungary",
      "Iceland",
      "Ireland",
      "Italy",
      "Kazakhstan",
      "Kosovo",
      "Latvia",
      "Liechtenstein",
      "Lithuania",
      "Luxembourg",
      "Malta",
      "Moldova",
      "Monaco",
      "Montenegro",
      "Netherlands",
      "North Macedonia (formerly Macedonia)",
      "Norway",
      "Poland",
      "Portugal",
      "Romania",
      "Russia",
      "San Marino",
      "Serbia",
      "Slovakia",
      "Slovenia",
      "Spain",
      "Sweden",
      "Switzerland",
      "Turkey",
      "Ukraine",
      "United Kingdom",
      "Vatican City",
    ],
  },
  {
    continent: "America",
    countries: [
      "Antigua and Barbuda",
      "Argentina",
      "Bahamas",
      "Barbados",
      "Belize",
      "Bolivia",
      "Brazil",
      "Canada",
      "Chile",
      "Colombia",
      "Costa Rica",
      "Cuba",
      "Dominica",
      "Dominican Republic",
      "Ecuador",
      "El Salvador",
      "Grenada",
      "Guatemala",
      "Guyana",
      "Haiti",
      "Honduras",
      "Jamaica",
      "Mexico",
      "Nicaragua",
      "Panama",
      "Paraguay",
      "Peru",
      "Saint Kitts and Nevis",
      "Saint Lucia",
      "Saint Vincent and the Grenadines",
      "Suriname",
      "Trinidad and Tobago",
      "United States",
      "Uruguay",
      "Venezuela",
    ],
  },
  {
    continent: "Australia",
    countries: [
      "Australia",
      "Fiji",
      "New Zealand",
      "Kiribati",
      "Marshall Islands",
      "Micronesia",
      "Nauru",
      "Palau",
      "Papua New Guinea",
      "Samoa",
    ],
  },
];
export const DDSearchValues = [
  {
    title: "All",
    value: "all",
  },
  {
    title: "Headline",
    value: "headline",
  },
  {
    title: "Author",
    value: "author_name",
  },
  {
    title: "Publication",
    value: "publication",
  },
  {
    title: "Subject",
    value: "reporting_subject",
  },
  {
    title: "Summary",
    value: "detail_summary",
  },
  {
    title: "Keyword",
    value: "keyword",
  },
  {
    title: "HeadSummary",
    value: "headsummary",
  },
  {
    title: "Remarks",
    value: "remarks",
  },
];
export const DDEditValues = [
  {
    id: 1,
    title: "Headline",
    value: "headline",
  },
  {
    id: 2,
    title: "Remarks",
    value: "remarks",
  },
  {
    id: 3,
    title: "Keyword",
    value: "keyword",
  },
  {
    id: 4,
    title: "Summary",
    value: "detail_summary",
  },
  {
    id: 5,
    title: "Author",
    value: "author_name",
  },

  {
    id: 6,
    title: "Head Summary",
    value: "headsummary",
  },
];
export const recordsPerPage = [200, 400, 600, 800, 1000];
// print
export const DDEditValuesForPrint = [
  {
    id: 1,
    title: "Headline",
    value: "headline",
  },
  {
    id: 2,
    title: "Remarks",
    value: "remarks",
  },
  {
    id: 3,
    title: "Keyword",
    value: "keyword",
  },
  {
    id: 4,
    title: "Summary",
    value: "detail_summary",
  },
  {
    id: 5,
    title: "Author",
    value: "author_name",
  },

  {
    id: 6,
    title: "Head Summary",
    value: "head_summary",
  },
  {
    id: 7,
    title: "Header Space",
    value: "header_space",
  },
];
export const categories = [
  {
    id: 1,
    title: "With Category",
    value: 1,
  },
  {
    id: 2,
    title: "No Category",
    value: 0,
  },
];
export const pubTypes = [
  {
    id: 1,
    title: "All",
    value: "ALL",
  },
  {
    id: 2,
    title: "Daily",
    value: "DAILY",
  },
  // {
  //   id: 3,
  //   title: "FortNightly",
  //   value: "FORTNIGHTLY",
  // },
  // {
  //   id: 4,
  //   title: "Monthly",
  //   value: "MONTHLY",
  // },
  // {
  //   id: 5,
  //   title: "Others",
  //   value: "OTHERS",
  // },
  {
    id: 3,
    title: "Magazine",
    value: "MAGAZINE",
  },
];
export const PrintDDEditValues = [
  {
    id: 1,
    title: "Headline",
    value: "headline",
  },
  {
    id: 2,
    title: "Remarks",
    value: "remarks",
  },
  {
    id: 3,
    title: "Keyword",
    value: "keyword",
  },
  {
    id: 4,
    title: "Summary",
    value: "detail_summary",
  },
  {
    id: 5,
    title: "Author",
    value: "author_name",
  },

  {
    id: 6,
    title: "Head Summary",
    value: "headsummary",
  },
];
export const qcPermissions = [
  { title: "Yes", value: 1 },
  { title: "No", value: 0 },
];
export const yesOrNo = ["Yes", "No"];

export const DDSearchValuesForPrint = [
  {
    title: "All",
    value: "all",
  },
  {
    title: "Headline",
    value: "headline",
  },
  {
    title: "Author",
    value: "author",
  },
  {
    title: "Publication",
    value: "publication",
  },
  {
    title: "Subject",
    value: "reporting_subject",
  },
  {
    title: "Summary",
    value: "detail_summary",
  },
  {
    title: "Keyword",
    value: "keyword",
  },
  {
    title: "HeadSummary",
    value: "head_summary",
  },
  {
    title: "Remarks",
    value: "remark",
  },
];

export const timeSlots = [
  "00:00",
  "00:30",
  "01:00",
  "01:30",
  "02:00",
  "02:30",
  "03:00",
  "03:30",
  "04:00",
  "04:30",
  "05:00",
  "05:30",
  "06:00",
  "06:30",
  "07:00",
  "07:30",
  "08:00",
  "08:30",
  "09:00",
  "09:30",
  "10:00",
  "10:30",
  "11:00",
  "11:30",
  "12:00",
  "12:30",
  "13:00",
  "13:30",
  "14:00",
  "14:30",
  "15:00",
  "15:30",
  "16:00",
  "16:30",
  "17:00",
  "17:30",
  "18:00",
  "18:30",
  "19:00",
  "19:30",
  "20:00",
  "20:30",
  "21:00",
  "21:30",
  "22:00",
  "22:30",
  "23:00",
  "23:30",
  "23:59",
];
